### ISSUE TITLE
Case sensitivity problems with Java MR91

### ISSUE THREAD

**Issue by ghannington** [genevaers/Run-Control-Apps#10]
In Java MR91 text in formula is case sensitive. This causes problems. I have added an example where a formula references a lookup path using upper case, but the definition of the path is in mixed case. 

See JBasespeclist.yaml , test " 17    STRFNU    Test left function with UPPER CASE formula   "
(This is in pull request #8 waiting to be approved/merged to main)

Java MR91 produces this error:

12155:1                                                      
INFO : runCompilers Now 11:42:09.584                         
INFO : ----------------------------                          
INFO : Compile the repository logic                          
INFO : ----------------------------                          
INFO : Compile view 12155 source 1                           
SEVERE : Errors detected                                     
SEVERE : Unkown Lookup CONCAT_CONCATTARG                     
SEVERE : 1 Errors detected. Logic Table will not be written. 
SEVERE : Number of format logic errors found: 1

**Comment by hammyau** [comment]
Gill, can you retest this and close off if no longer an issue.

**Comment by ghannington** [comment]
Retested and STRFNU now runs to completion.
