### ISSUE TITLE
Consider making jzos and sdsf optional jars

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/Run-Control-Apps#12]
Here are notes from Ian on this potential enhancement:

to find the dependencies and where things are used it's best to use VS Code's "Find in Files" option from the edit menu.
It shows the poms that use say sdsf or jzos.
And it shows where they packages are referred to.

In order to make a mainframe version we will need to refactor the code too.
Extract the places where the jzos or sdsf calls are made to base abstract classes.
Then we can include whichever instantiations we want via some scripting or something.

The sdsf jar is used only in the PETestFramework. Since it monitors the spool to manage the jobs.
Note the actual jar is called isfcall.jar and the mvsInstallJars script installs it into Maven as sdsf.
I tried to make it clearer what we were using it for.

The jzos jar is used in both the Test framework and the utilities.
Java MR91 uses the classes in the utilities to read and write MVS datasets.
We could create an MVS Utilities to manage the file IO and the spool calls etc.
Then use them only in an MVS targeted build.

Just thinking of the top of my head there. Not sure if it is worth doing that just yet but could well be worth doing later.

**Comment by hammyau** [comment]
This has been done via Maven profiles as part of the RCApps 1.1.0_RC1 build
