### ISSUE TITLE
ssh assumed in grammer install script

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/Run-Control-Apps#13]
deleted m2 repository and the git repo, recloned mr91, and the install grammer script looped around with failures.

[INFO] Building GenevaERS Utilites Pre-Build 1.0.2
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:3.1.0:exec (Run Script) @ utilsprebuild ---
Clone the grammar
Cloning into '../Grammar'...
Connection reset by 140.82.114.3 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
prebuild.sh: line 23: cd: ../Grammar: No such file or directory
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< org.genevaers:utilsprebuild >---------------------
[INFO] Building GenevaERS Utilites Pre-Build 1.0.2
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:3.1.0:exec (Run Script) @ utilsprebuild ---
Clone the grammar
Cloning into '../Grammar'...
Connection reset by 140.82.114.3 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
prebuild.sh: line 23: cd: ../Grammar: No such file or directory
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< org.genevaers:utilsprebuild >---------------------
[INFO] Building GenevaERS Utilites Pre-Build 1.0.2
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:3.1.0:exec (Run Script) @ utilsprebuild ---
Clone the grammar
Cloning into '../Grammar'...
Connection reset by 140.82.114.3 port 22
fatal: Could not read from remote repository.

**Comment by hammyau** [comment]
Kip, is this still an issue?

**Comment by KipTwitchell** [comment]
I think we figured the way around it.
